batch_size: 4
data: spider-tvt
eval_gen:
  max_length: 1024
  min_length: 5
  num_beams: 5
learning_rate: 0.002
model: state-spaces/mamba-1.4b
no_save: false
num_epochs: 10
peft: cfg/peft/sd_lora/500it/n0.95_d0.99.json
prec: bf16
seed: 42
